trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  aciName: 'aci-webapi'
  imageRepository: 'WebApi'
  containerRegistry: 'acrtechchallenge02.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/WebAPI/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: FileTransform@1
      inputs:
        folderPath: 'WebAPI'
        fileType: 'json'
        targetFiles: 'appsettings.json'
    - task: Docker@2
      inputs:
        containerRegistry: 'acrtechchallenge02'
        repository: 'webapi'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'acrtechchallenge02'
        repository: 'webapi'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students (c0b47b0c-425a-4257-bf4a-1b1051a06839)'
        scriptType: bash
        scriptLocation: 'inlineScript'
        inlineScript: 'az container restart --name $(aciName) --resource-group $(TechChallenge02.resourceGroupName)'