trigger:
- main

resources:
- repo: self

variables:
 - group: 'WebAPI'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: FileTransform@1
      inputs:
        folderPath: 'WebAPI'
        fileType: 'json'
        targetFiles: 'appsettings.json'
    - task: Docker@2
      inputs:
        containerRegistry: 'acrtechchallenge02'
        repository: 'webapi'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'acrtechchallenge02'
        repository: 'webapi'
        command: 'push'
        tags: |
          $(tag)
          latest
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students (c0b47b0c-425a-4257-bf4a-1b1051a06839)'
        scriptType: bash
        scriptLocation: 'inlineScript'
        inlineScript: 'az container restart --name $(aciName) --resource-group $(TechChallenge02.resourceGroupName)'