trigger:
  branches:
    include:
      - main
  paths:
    include:
      - WebApp/*

resources:
- repo: self

variables:
 - group: 'WebApp'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: FileTransform@1
      inputs:
        folderPath: 'WebApp'
        fileType: 'json'
        targetFiles: 'appsettings.json'

    - task: Docker@2
      inputs:
        containerRegistry: 'acrtechchallenge02'
        repository: 'webapp'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(tag)
          latest

    - task: Docker@2
      inputs:
        containerRegistry: 'acrtechchallenge02'
        repository: '$(acrRepository)'
        command: 'push'
        tags: |
          $(tag)
          latest

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students (c0b47b0c-425a-4257-bf4a-1b1051a06839)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          try {
              az container restart --name $(aciName) --resource-group $(resourceGroupName)
          }
          catch {
              Write-Host "Error: $($_.Exception.Message)"
          }
          